// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6I9FRdp161iQyjzETFtIowNN383RWbgo',
    appId: '1:218829951210:web:c634390143ad9fb95dc793',
    messagingSenderId: '218829951210',
    projectId: 'campuseat-23b1d',
    authDomain: 'campuseat-23b1d.firebaseapp.com',
    storageBucket: 'campuseat-23b1d.appspot.com',
    measurementId: 'G-JXTVN7WM2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYAPEIFLctaqtomAu6-XBeU7MqUs1G04o',
    appId: '1:218829951210:android:b6539f235942c49a5dc793',
    messagingSenderId: '218829951210',
    projectId: 'campuseat-23b1d',
    storageBucket: 'campuseat-23b1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0M8Z3d_I_vhBwzwpCrm8kX4tXnY2FUPk',
    appId: '1:218829951210:ios:92daca5f0652ce655dc793',
    messagingSenderId: '218829951210',
    projectId: 'campuseat-23b1d',
    storageBucket: 'campuseat-23b1d.appspot.com',
    iosBundleId: 'com.example.campuseat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0M8Z3d_I_vhBwzwpCrm8kX4tXnY2FUPk',
    appId: '1:218829951210:ios:92daca5f0652ce655dc793',
    messagingSenderId: '218829951210',
    projectId: 'campuseat-23b1d',
    storageBucket: 'campuseat-23b1d.appspot.com',
    iosBundleId: 'com.example.campuseat',
  );
}
